In [1]:
import pandas as pd

In [2]:
discharge = pd.read_csv("/projects/standard/xie00469/shared/mimic-iv-note/2.2/note/discharge.csv")
discharge

,note_id,subject_id,hadm_id,note_type,note_seq,charttime,storetime,text
0,10000032-DS-21,10000032,22595853,DS,21,2180-05-07 00:00:00,2180-05-09 15:26:00,\nName: ___ Unit No: _...
1,10000032-DS-22,10000032,22841357,DS,22,2180-06-27 00:00:00,2180-07-01 10:15:00,\nName: ___ Unit No: _...
2,10000032-DS-23,10000032,29079034,DS,23,2180-07-25 00:00:00,2180-07-25 21:42:00,\nName: ___ Unit No: _...
3,10000032-DS-24,10000032,25742920,DS,24,2180-08-07 00:00:00,2180-08-10 05:43:00,\nName: ___ Unit No: _...
4,10000084-DS-17,10000084,23052089,DS,17,2160-11-25 00:00:00,2160-11-25 15:09:00,\nName: ___ Unit No: __...
...,...,...,...,...,...,...,...,...
331788,19999828-DS-6,19999828,29734428,DS,6,2147-08-04 00:00:00,2147-08-12 15:36:00,\nName: ___ Unit No: ___...
331789,19999828-DS-7,19999828,25744818,DS,7,2149-01-18 00:00:00,2149-01-19 07:03:00,\nName: ___ Unit No: ___...
331790,19999840-DS-20,19999840,26071774,DS,20,2164-07-28 00:00:00,2164-07-29 14:52:00,\nName: ___ Unit No: ___\...
331791,19999840-DS-21,19999840,21033226,DS,21,2164-09-17 00:00:00,2164-09-18 01:36:00,\nName: ___ Unit No: ___\...
331792,19999987-DS-2,19999987,23865745,DS,2,2145-11-11 00:00:00,2145-11-11 13:13:00,\nName: ___ Unit No: __...

In [4]:
radiology = pd.read_csv("~/radiology.csv")
radiology

,note_id,subject_id,hadm_id,note_type,note_seq,charttime,storetime,text
0,10000032-RR-14,10000032,22595853.0,RR,14,2180-05-06 21:19:00,2180-05-06 23:32:00,EXAMINATION: CHEST (PA AND LAT)\n\nINDICATION...
1,10000032-RR-15,10000032,22595853.0,RR,15,2180-05-06 23:00:00,2180-05-06 23:26:00,EXAMINATION: LIVER OR GALLBLADDER US (SINGLE ...
2,10000032-RR-16,10000032,22595853.0,RR,16,2180-05-07 09:55:00,2180-05-07 11:15:00,"INDICATION: ___ HCV cirrhosis c/b ascites, hi..."
3,10000032-RR-18,10000032,NaN,RR,18,2180-06-03 12:46:00,2180-06-03 14:01:00,EXAMINATION: Ultrasound-guided paracentesis.\...
4,10000032-RR-20,10000032,NaN,RR,20,2180-07-08 13:18:00,2180-07-08 14:15:00,EXAMINATION: Paracentesis\n\nINDICATION: ___...
...,...,...,...,...,...,...,...,...
2321350,19999987-RR-17,19999987,23865745.0,RR,17,2145-11-02 22:37:00,2145-11-03 18:55:00,"HISTORY: ___, with left occipital bleeding. ..."
2321351,19999987-RR-18,19999987,23865745.0,RR,18,2145-11-03 04:35:00,2145-11-03 10:46:00,INDICATION: ___ female intubated for head ble...
2321352,19999987-RR-19,19999987,23865745.0,RR,19,2145-11-03 16:40:00,2145-11-04 08:36:00,HISTORY: ___ woman with left occipital hemorr...
2321353,19999987-RR-20,19999987,23865745.0,RR,20,2145-11-04 05:10:00,2145-11-04 08:58:00,PORTABLE CHEST OF ___\n\nCOMPARISON: ___ radi...
2321354,19999987-RR-21,19999987,23865745.0,RR,21,2145-11-07 15:18:00,2145-11-08 16:44:00,DATE OF SERVICE: ___.\n\nPRE-OPERATIVE DIAGNO...

In [5]:
radiology.iloc[0]["text"]

'EXAMINATION:  CHEST (PA AND LAT)\n\nINDICATION:  ___ with new onset ascites  // eval for infection\n\nTECHNIQUE:  Chest PA and lateral\n\nCOMPARISON:  None.\n\nFINDINGS: \n\nThere is no focal consolidation, pleural effusion or pneumothorax.  Bilateral\nnodular opacities that most likely represent nipple shadows. The\ncardiomediastinal silhouette is normal.  Clips project over the left lung,\npotentially within the breast. The imaged upper abdomen is unremarkable.\nChronic deformity of the posterior left sixth and seventh ribs are noted.\n\nIMPRESSION: \n\nNo acute cardiopulmonary process.\n'

In [6]:
radiology[radiology["subject_id"] == 19512408]

,note_id,subject_id,hadm_id,note_type,note_seq,charttime,storetime,text
2205769,19512408-RR-10,19512408,NaN,RR,10,2182-07-07 18:49:00,2182-07-07 19:58:00,EXAMINATION: CT abdomen pelvis\n\nINDICATION:...
2205770,19512408-RR-11,19512408,NaN,RR,11,2182-09-13 15:33:00,2182-09-13 17:23:00,"EXAMINATION: US NECK, SOFT TISSUE\n\nINDICATI..."
2205771,19512408-RR-12,19512408,NaN,RR,12,2182-11-30 08:25:00,2182-11-30 09:26:00,"EXAMINATION: PELVIS U.S., TRANSVAGINAL\n\nIND..."
2205772,19512408-RR-7,19512408,22907124.0,RR,7,2181-10-02 13:48:00,2181-10-02 14:58:00,INDICATION: ___ with blister at ___ finger MC...
2205773,19512408-RR-8,19512408,NaN,RR,8,2182-07-07 15:52:00,2182-07-07 17:09:00,"EXAMINATION: PELVIS, NON-OBSTETRIC\n\nINDICAT..."
2205774,19512408-RR-9,19512408,NaN,RR,9,2182-07-07 15:52:00,2182-07-07 17:16:00,EXAMINATION: US APPENDIX\n\nINDICATION: ___ ...

In [7]:
print(len(radiology))
radiology['note_id'].nunique()

2321355

2321355

In [8]:
radiology.iloc[0]['text']

'EXAMINATION:  CHEST (PA AND LAT)\n\nINDICATION:  ___ with new onset ascites  // eval for infection\n\nTECHNIQUE:  Chest PA and lateral\n\nCOMPARISON:  None.\n\nFINDINGS: \n\nThere is no focal consolidation, pleural effusion or pneumothorax.  Bilateral\nnodular opacities that most likely represent nipple shadows. The\ncardiomediastinal silhouette is normal.  Clips project over the left lung,\npotentially within the breast. The imaged upper abdomen is unremarkable.\nChronic deformity of the posterior left sixth and seventh ribs are noted.\n\nIMPRESSION: \n\nNo acute cardiopulmonary process.\n'

In [9]:
# radiology_detail = pd.read_csv("physionet.org/files/mimic-iv-note/2.2/note/radiology_detail.csv")
# radiology_detail

In [10]:
master_dataset = pd.read_csv("master_dataset.csv")
master_dataset

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,eci_Depression,ed_temperature_last,ed_heartrate_last,ed_resprate_last,ed_o2sat_last,ed_sbp_last,ed_dbp_last,ed_pain_last,n_med,n_medrecon
0,335314,10000032,22595853.0,33258284,2180-05-06 19:17:00,2180-05-06 23:30:00,52,F,2180,NaN,...,0,97.7,79.0,16.0,98.0,107.0,60.0,0.0,0.0,9.0
1,335315,10000032,22841357.0,38112554,2180-06-26 15:54:00,2180-06-26 21:31:00,52,F,2180,NaN,...,1,97.9,86.0,17.0,93.0,96.0,57.0,5.0,3.0,12.0
2,335316,10000032,29079034.0,32952584,2180-07-22 16:24:00,2180-07-23 05:54:00,52,F,2180,NaN,...,1,98.2,85.0,18.0,98.0,81.0,38.0,0.0,2.0,14.0
3,335317,10000032,29079034.0,39399961,2180-07-23 05:54:00,2180-07-23 14:00:00,52,F,2180,NaN,...,1,99.0,96.0,18.0,97.0,86.0,45.0,NaN,8.0,14.0
4,335318,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,52,F,2180,NaN,...,1,98.1,91.0,18.0,99.0,98.0,60.0,NaN,6.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448967,167406,19999784,25715748.0,34149746,2119-08-11 09:15:00,2119-08-11 13:40:00,57,M,2119,NaN,...,0,98.1,72.0,16.0,100.0,131.0,92.0,0.0,1.0,8.0
448968,167407,19999828,29734428.0,30712109,2147-07-17 17:18:00,2147-07-18 17:34:00,46,F,2147,NaN,...,0,99.6,78.0,17.0,99.0,108.0,87.0,9.0,11.0,8.0
448969,167408,19999828,25744818.0,32917002,2149-01-08 09:11:00,2149-01-08 18:12:00,46,F,2147,NaN,...,0,98.1,109.0,15.0,96.0,111.0,78.0,4.0,8.0,11.0
448970,167409,19999914,NaN,32002659,2158-12-24 11:41:00,2158-12-24 11:41:00,49,F,2158,NaN,...,0,99.5,81.0,10.0,100.0,93.0,55.0,0.0,5.0,0.0
448971,335313,19999987,23865745.0,34731548,2145-11-02 19:28:00,2145-11-02 22:59:00,57,F,2145,NaN,...,0,99.3,103.0,20.0,NaN,113.0,79.0,NaN,4.0,0.0

In [11]:
len(master_dataset)

448972

In [12]:
master_dataset['stay_id'].nunique()

448972

In [13]:
master_dataset["intime"].isna().sum()

0

In [14]:
master_dataset["admittime"].isna().sum()

234562

In [15]:
for column in master_dataset.columns:
    print(column)

index
subject_id
hadm_id
stay_id
intime
outtime
anchor_age
gender
anchor_year
dod
admittime
dischtime
deathtime
ethnicity
edregtime
edouttime
insurance
in_year
age
outcome_inhospital_mortality
ed_death
before_ed_mortality
ed_los
intime_icu
time_to_icu_transfer
outcome_icu_transfer_12h
outcome_hospitalization
outcome_critical
n_ed_30d
n_ed_90d
n_ed_365d
next_ed_visit_time
next_ed_visit_time_diff
outcome_ed_revisit_3d
n_hosp_30d
n_hosp_90d
n_hosp_365d
n_icu_30d
n_icu_90d
n_icu_365d
ed_los_hours
time_to_icu_transfer_hours
next_ed_visit_time_diff_days
triage_temperature
triage_heartrate
triage_resprate
triage_o2sat
triage_sbp
triage_dbp
triage_pain
triage_acuity
chiefcomplaint
chiefcom_chest_pain
chiefcom_abdominal_pain
chiefcom_headache
chiefcom_shortness_of_breath
chiefcom_back_pain
chiefcom_cough
chiefcom_nausea_vomiting
chiefcom_fever_chills
chiefcom_syncope
chiefcom_dizziness
cci_MI
cci_CHF
cci_PVD
cci_Stroke
cci_Dementia
cci_Pulmonary
cci_Rheumatic
cci_PUD
cci_Liver1
cci_DM1
cci_DM2
cci_Paralysis
cci_Renal
cci_Cancer1
cci_Liver2
cci_Cancer2
cci_HIV
eci_CHF
eci_Arrhythmia
eci_Valvular
eci_PHTN
eci_PVD
eci_HTN1
eci_HTN2
eci_Paralysis
eci_NeuroOther
eci_Pulmonary
eci_DM1
eci_DM2
eci_Hypothyroid
eci_Renal
eci_Liver
eci_PUD
eci_HIV
eci_Lymphoma
eci_Tumor2
eci_Tumor1
eci_Rheumatic
eci_Coagulopathy
eci_Obesity
eci_WeightLoss
eci_FluidsLytes
eci_BloodLoss
eci_Anemia
eci_Alcohol
eci_Drugs
eci_Psychoses
eci_Depression
ed_temperature_last
ed_heartrate_last
ed_resprate_last
ed_o2sat_last
ed_sbp_last
ed_dbp_last
ed_pain_last
n_med
n_medrecon

In [16]:
import pandas as pd

TIME_COL      = "outtime"
NOTE_TIME_COL = "charttime"
TEXT_COL      = "text"
OUT_COL       = "discharge_notes"
OUT_ID_COL    = "discharge_note_id"

NORMALIZE_TEXT = True

master = master_dataset.copy()
notes  = discharge.copy()

master[TIME_COL] = pd.to_datetime(master[TIME_COL], errors="coerce")
notes[NOTE_TIME_COL] = pd.to_datetime(notes[NOTE_TIME_COL], errors="coerce")

master["subject_id"] = pd.to_numeric(master["subject_id"], errors="coerce").astype("Int64")
notes["subject_id"]  = pd.to_numeric(notes["subject_id"],  errors="coerce").astype("Int64")

master = master.dropna(subset=["subject_id", TIME_COL]).copy()
notes  = notes.dropna(subset=["subject_id", NOTE_TIME_COL, TEXT_COL]).copy()

master["subject_id"] = master["subject_id"].astype("int64")
notes["subject_id"]  = notes["subject_id"].astype("int64")

master["_row_id"] = master.index.astype("int64")

max_outtime = master[TIME_COL].max()
notes = notes[notes[NOTE_TIME_COL] <= max_outtime].copy()

if NORMALIZE_TEXT:
    notes["_text_key"] = (
        notes[TEXT_COL].astype(str)
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )
else:
    notes["_text_key"] = notes[TEXT_COL].astype(str)

master_sorted = master.sort_values([TIME_COL, "subject_id"], kind="mergesort").reset_index(drop=True)
notes_sorted  = notes.sort_values([NOTE_TIME_COL, "subject_id"], kind="mergesort").reset_index(drop=True)

cols_from_notes = ["subject_id", NOTE_TIME_COL, TEXT_COL, "_text_key"]
if "note_id" in notes_sorted.columns:
    cols_from_notes.insert(3, "note_id")

cand = pd.merge_asof(
    master_sorted,
    notes_sorted[cols_from_notes],
    by="subject_id",
    left_on=TIME_COL,
    right_on=NOTE_TIME_COL,
    direction="backward",
    allow_exact_matches=True,
)

matched = cand.dropna(subset=["_text_key"]).copy()
matched["_gap_sec"] = (matched[TIME_COL] - matched[NOTE_TIME_COL]).dt.total_seconds()

final_assignments = (
    matched.sort_values(["_text_key", "_gap_sec"], kind="mergesort")
           .drop_duplicates("_text_key", keep="first")
)

keep_cols = ["_row_id", TEXT_COL]
rename_map = {TEXT_COL: OUT_COL}

if "note_id" in final_assignments.columns:
    keep_cols.insert(1, "note_id")
    rename_map["note_id"] = OUT_ID_COL

mapping = final_assignments[keep_cols].rename(columns=rename_map)

master_out = master_dataset.copy()
master_out["_row_id"] = master_out.index.astype("int64")

master_out = master_out.merge(mapping, on="_row_id", how="left").drop(columns=["_row_id"])
master_dataset = master_out

In [17]:
master_dataset

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,ed_heartrate_last,ed_resprate_last,ed_o2sat_last,ed_sbp_last,ed_dbp_last,ed_pain_last,n_med,n_medrecon,discharge_note_id,discharge_notes
0,335314,10000032,22595853.0,33258284,2180-05-06 19:17:00,2180-05-06 23:30:00,52,F,2180,NaN,...,79.0,16.0,98.0,107.0,60.0,0.0,0.0,9.0,NaN,NaN
1,335315,10000032,22841357.0,38112554,2180-06-26 15:54:00,2180-06-26 21:31:00,52,F,2180,NaN,...,86.0,17.0,93.0,96.0,57.0,5.0,3.0,12.0,10000032-DS-21,\nName: ___ Unit No: _...
2,335316,10000032,29079034.0,32952584,2180-07-22 16:24:00,2180-07-23 05:54:00,52,F,2180,NaN,...,85.0,18.0,98.0,81.0,38.0,0.0,2.0,14.0,10000032-DS-22,\nName: ___ Unit No: _...
3,335317,10000032,29079034.0,39399961,2180-07-23 05:54:00,2180-07-23 14:00:00,52,F,2180,NaN,...,96.0,18.0,97.0,86.0,45.0,NaN,8.0,14.0,NaN,NaN
4,335318,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,52,F,2180,NaN,...,91.0,18.0,99.0,98.0,60.0,NaN,6.0,7.0,10000032-DS-23,\nName: ___ Unit No: _...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448967,167406,19999784,25715748.0,34149746,2119-08-11 09:15:00,2119-08-11 13:40:00,57,M,2119,NaN,...,72.0,16.0,100.0,131.0,92.0,0.0,1.0,8.0,19999784-DS-9,\nName: ___ Unit No: __...
448968,167407,19999828,29734428.0,30712109,2147-07-17 17:18:00,2147-07-18 17:34:00,46,F,2147,NaN,...,78.0,17.0,99.0,108.0,87.0,9.0,11.0,8.0,NaN,NaN
448969,167408,19999828,25744818.0,32917002,2149-01-08 09:11:00,2149-01-08 18:12:00,46,F,2147,NaN,...,109.0,15.0,96.0,111.0,78.0,4.0,8.0,11.0,19999828-DS-6,\nName: ___ Unit No: ___...
448970,167409,19999914,NaN,32002659,2158-12-24 11:41:00,2158-12-24 11:41:00,49,F,2158,NaN,...,81.0,10.0,100.0,93.0,55.0,0.0,5.0,0.0,NaN,NaN
448971,335313,19999987,23865745.0,34731548,2145-11-02 19:28:00,2145-11-02 22:59:00,57,F,2145,NaN,...,103.0,20.0,NaN,113.0,79.0,NaN,4.0,0.0,NaN,NaN

In [18]:
check = master_dataset[
    master_dataset["discharge_note_id"].notna()
].copy()

audit = check.merge(
    discharge[["note_id", "charttime"]].drop_duplicates("note_id"),
    left_on="discharge_note_id",
    right_on="note_id",
    how="left"
)

bad = audit[audit["charttime"] > audit["outtime"]]

print("Bad assignments:", len(bad))

Bad assignments: 0

In [19]:
master_dataset['stay_id'].nunique()

448972

In [20]:
master_dataset['discharge_notes'].isna().sum()

324280

In [21]:
master_dataset.loc[0]['intime']

'2180-05-06 19:17:00'

In [23]:
import pandas as pd

master = master_dataset.copy()
notes = radiology.copy()

master["outtime"] = pd.to_datetime(master["outtime"], errors="coerce")
notes["charttime"] = pd.to_datetime(notes["charttime"], errors="coerce")

master["subject_id"] = master["subject_id"].astype("int64")
notes["subject_id"] = notes["subject_id"].astype("int64")

master = master.dropna(subset=["subject_id", "outtime"])
notes = notes.dropna(subset=["subject_id", "charttime", "text"])

notes["_text_key"] = (
    notes["text"]
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

master["_row_id"] = master.index.astype("int64")

max_outtime = master["outtime"].max()
notes = notes[notes["charttime"] <= max_outtime]

master_sorted = master.sort_values(["outtime", "subject_id"], kind="mergesort").reset_index(drop=True)
notes_sorted = notes.sort_values(["charttime", "subject_id"], kind="mergesort").reset_index(drop=True)

cand = pd.merge_asof(
    master_sorted,
    notes_sorted[["subject_id", "charttime", "note_id", "text", "_text_key"]],
    by="subject_id",
    left_on="outtime",
    right_on="charttime",
    direction="backward",
    allow_exact_matches=True
)

matched = cand.dropna(subset=["_text_key"]).copy()
matched["_gap_sec"] = (matched["outtime"] - matched["charttime"]).dt.total_seconds()

final_assignments = (
    matched.sort_values(["_text_key", "_gap_sec"], kind="mergesort")
           .drop_duplicates("_text_key", keep="first")
)

mapping = final_assignments[["_row_id", "note_id", "text"]].rename(
    columns={
        "note_id": "radiology_note_id",
        "text": "radiology_notes"
    }
)

master_out = master_dataset.copy()
master_out["_row_id"] = master_out.index.astype("int64")

master_out = master_out.merge(mapping, on="_row_id", how="left").drop(columns=["_row_id"])

master_dataset = master_out

In [24]:
master_dataset

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,ed_o2sat_last,ed_sbp_last,ed_dbp_last,ed_pain_last,n_med,n_medrecon,discharge_note_id,discharge_notes,radiology_note_id,radiology_notes
0,335314,10000032,22595853.0,33258284,2180-05-06 19:17:00,2180-05-06 23:30:00,52,F,2180,NaN,...,98.0,107.0,60.0,0.0,0.0,9.0,NaN,NaN,10000032-RR-15,EXAMINATION: LIVER OR GALLBLADDER US (SINGLE ...
1,335315,10000032,22841357.0,38112554,2180-06-26 15:54:00,2180-06-26 21:31:00,52,F,2180,NaN,...,93.0,96.0,57.0,5.0,3.0,12.0,10000032-DS-21,\nName: ___ Unit No: _...,10000032-RR-23,EXAMINATION: CHEST (PA AND LAT)\n\nINDICATION...
2,335316,10000032,29079034.0,32952584,2180-07-22 16:24:00,2180-07-23 05:54:00,52,F,2180,NaN,...,98.0,81.0,38.0,0.0,2.0,14.0,10000032-DS-22,\nName: ___ Unit No: _...,10000032-RR-24,EXAMINATION: Ultrasound-guided paracentesis.\...
3,335317,10000032,29079034.0,39399961,2180-07-23 05:54:00,2180-07-23 14:00:00,52,F,2180,NaN,...,97.0,86.0,45.0,NaN,8.0,14.0,NaN,NaN,10000032-RR-45,EXAMINATION: CHEST (PORTABLE AP)\n\nINDICATIO...
4,335318,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,52,F,2180,NaN,...,99.0,98.0,60.0,NaN,6.0,7.0,10000032-DS-23,\nName: ___ Unit No: _...,10000032-RR-46,INDICATION: ___ year old woman with cirrhosis...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448967,167406,19999784,25715748.0,34149746,2119-08-11 09:15:00,2119-08-11 13:40:00,57,M,2119,NaN,...,100.0,131.0,92.0,0.0,1.0,8.0,19999784-DS-9,\nName: ___ Unit No: __...,19999784-RR-34,EXAMINATION: CT L-SPINE W/O CONTRAST Q331 CT ...
448968,167407,19999828,29734428.0,30712109,2147-07-17 17:18:00,2147-07-18 17:34:00,46,F,2147,NaN,...,99.0,108.0,87.0,9.0,11.0,8.0,NaN,NaN,19999828-RR-20,INDICATION: ___ year old woman with new right...
448969,167408,19999828,25744818.0,32917002,2149-01-08 09:11:00,2149-01-08 18:12:00,46,F,2147,NaN,...,96.0,111.0,78.0,4.0,8.0,11.0,19999828-DS-6,\nName: ___ Unit No: ___...,19999828-RR-25,EXAMINATION: SECOND OPINION CT TORSO\n\nINDIC...
448970,167409,19999914,NaN,32002659,2158-12-24 11:41:00,2158-12-24 11:41:00,49,F,2158,NaN,...,100.0,93.0,55.0,0.0,5.0,0.0,NaN,NaN,NaN,NaN
448971,335313,19999987,23865745.0,34731548,2145-11-02 19:28:00,2145-11-02 22:59:00,57,F,2145,NaN,...,NaN,113.0,79.0,NaN,4.0,0.0,NaN,NaN,19999987-RR-17,"HISTORY: ___, with left occipital bleeding. ..."

In [25]:
check = master_dataset[
    master_dataset["radiology_note_id"].notna()
].copy()

audit = check.merge(
    radiology[["note_id", "charttime"]].drop_duplicates("note_id"),
    left_on="radiology_note_id",
    right_on="note_id",
    how="left"
)

bad = audit[audit["charttime"] > audit["outtime"]]

print("Bad assignments:", len(bad))

Bad assignments: 0

In [26]:
master_dataset = master_dataset[(pd.isna(master_dataset['discharge_notes']) == False) | (pd.isna(master_dataset['radiology_notes']) == False)]
master_dataset

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,ed_o2sat_last,ed_sbp_last,ed_dbp_last,ed_pain_last,n_med,n_medrecon,discharge_note_id,discharge_notes,radiology_note_id,radiology_notes
0,335314,10000032,22595853.0,33258284,2180-05-06 19:17:00,2180-05-06 23:30:00,52,F,2180,NaN,...,98.0,107.0,60.0,0.0,0.0,9.0,NaN,NaN,10000032-RR-15,EXAMINATION: LIVER OR GALLBLADDER US (SINGLE ...
1,335315,10000032,22841357.0,38112554,2180-06-26 15:54:00,2180-06-26 21:31:00,52,F,2180,NaN,...,93.0,96.0,57.0,5.0,3.0,12.0,10000032-DS-21,\nName: ___ Unit No: _...,10000032-RR-23,EXAMINATION: CHEST (PA AND LAT)\n\nINDICATION...
2,335316,10000032,29079034.0,32952584,2180-07-22 16:24:00,2180-07-23 05:54:00,52,F,2180,NaN,...,98.0,81.0,38.0,0.0,2.0,14.0,10000032-DS-22,\nName: ___ Unit No: _...,10000032-RR-24,EXAMINATION: Ultrasound-guided paracentesis.\...
3,335317,10000032,29079034.0,39399961,2180-07-23 05:54:00,2180-07-23 14:00:00,52,F,2180,NaN,...,97.0,86.0,45.0,NaN,8.0,14.0,NaN,NaN,10000032-RR-45,EXAMINATION: CHEST (PORTABLE AP)\n\nINDICATIO...
4,335318,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,52,F,2180,NaN,...,99.0,98.0,60.0,NaN,6.0,7.0,10000032-DS-23,\nName: ___ Unit No: _...,10000032-RR-46,INDICATION: ___ year old woman with cirrhosis...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448966,167405,19999784,24935234.0,37972930,2119-07-09 17:38:00,2119-07-10 00:04:00,57,M,2119,NaN,...,99.0,142.0,80.0,3.0,0.0,1.0,19999784-DS-7,\nName: ___ Unit No: __...,19999784-RR-23,EXAMINATION: MR ___ AND W/O CONTRAST ___ MR S...
448967,167406,19999784,25715748.0,34149746,2119-08-11 09:15:00,2119-08-11 13:40:00,57,M,2119,NaN,...,100.0,131.0,92.0,0.0,1.0,8.0,19999784-DS-9,\nName: ___ Unit No: __...,19999784-RR-34,EXAMINATION: CT L-SPINE W/O CONTRAST Q331 CT ...
448968,167407,19999828,29734428.0,30712109,2147-07-17 17:18:00,2147-07-18 17:34:00,46,F,2147,NaN,...,99.0,108.0,87.0,9.0,11.0,8.0,NaN,NaN,19999828-RR-20,INDICATION: ___ year old woman with new right...
448969,167408,19999828,25744818.0,32917002,2149-01-08 09:11:00,2149-01-08 18:12:00,46,F,2147,NaN,...,96.0,111.0,78.0,4.0,8.0,11.0,19999828-DS-6,\nName: ___ Unit No: ___...,19999828-RR-25,EXAMINATION: SECOND OPINION CT TORSO\n\nINDIC...
448971,335313,19999987,23865745.0,34731548,2145-11-02 19:28:00,2145-11-02 22:59:00,57,F,2145,NaN,...,NaN,113.0,79.0,NaN,4.0,0.0,NaN,NaN,19999987-RR-17,"HISTORY: ___, with left occipital bleeding. ..."

In [27]:
# Check for conflicting hospitalization outcomes
conflict_hosp = (
    master_dataset.groupby("radiology_notes")["outcome_hospitalization"]
    .nunique()
    .reset_index(name="n_unique")
)

conflict_hosp = conflict_hosp[conflict_hosp["n_unique"] > 1]

print("Notes with conflicting hospitalization outcomes:", len(conflict_hosp))


# Check for conflicting critical outcomes
conflict_crit = (
    master_dataset.groupby("radiology_notes")["outcome_critical"]
    .nunique()
    .reset_index(name="n_unique")
)

conflict_crit = conflict_crit[conflict_crit["n_unique"] > 1]

print("Notes with conflicting critical outcomes:", len(conflict_crit))

Notes with conflicting hospitalization outcomes: 0
Notes with conflicting critical outcomes: 0

In [28]:
import pandas as pd

def chunk_generator(df, chunk_size=10000):
    for start in range(0, len(df), chunk_size):
        yield df.iloc[start:start + chunk_size].copy()

def safe_combine(d_note, r_note):
    if pd.isna(d_note) and pd.isna(r_note):
        return pd.NA
    elif pd.isna(d_note):
        return r_note
    elif pd.isna(r_note):
        return d_note
    else:
        return f"{d_note} {r_note}"

def process_and_save(master_dataset, output_path, chunk_size=10000):
    with open(output_path, 'w', encoding='utf-8') as f_out:
        header_written = False

        for chunk in chunk_generator(master_dataset, chunk_size):
            # Process chunk
            chunk['notes'] = [
                safe_combine(d, r)
                for d, r in zip(chunk['discharge_notes'], chunk['radiology_notes'])
            ]

            # Write to CSV incrementally
            chunk.to_csv(f_out, index=False, header=not header_written)
            header_written = True

process_and_save(master_dataset, 'master_dataset_notes_DISPOSITION.csv', chunk_size=10000)

In [28]:
notes_df = pd.read_csv('master_dataset_notes_DISPOSITION.csv')
notes_df

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,ed_sbp_last,ed_dbp_last,ed_pain_last,n_med,n_medrecon,discharge_note_id,discharge_notes,radiology_note_id,radiology_notes,notes
0,335315,10000032,22841357.0,38112554,2180-06-26 15:54:00,2180-06-26 21:31:00,52,F,2180,NaN,...,96.0,57.0,5.0,3.0,12.0,10000032-DS-21,\nName: ___ Unit No: _...,10000032-RR-18,EXAMINATION: Ultrasound-guided paracentesis.\...,\nName: ___ Unit No: _...
1,335316,10000032,29079034.0,32952584,2180-07-22 16:24:00,2180-07-23 05:54:00,52,F,2180,NaN,...,81.0,38.0,0.0,2.0,14.0,10000032-DS-22,\nName: ___ Unit No: _...,10000032-RR-24,EXAMINATION: Ultrasound-guided paracentesis.\...,\nName: ___ Unit No: _...
2,335318,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,52,F,2180,NaN,...,98.0,60.0,NaN,6.0,7.0,10000032-DS-23,\nName: ___ Unit No: _...,10000032-RR-42,EXAMINATION: PARACENTESIS\n\nINDICATION: ___...,\nName: ___ Unit No: _...
3,56672,10000084,29888819.0,36954971,2160-12-27 18:32:00,2160-12-28 16:07:00,72,M,2160,NaN,...,119.0,84.0,0.0,1.0,6.0,10000084-DS-17,\nName: ___ Unit No: __...,10000084-RR-13,EXAMINATION: CT HEAD W/O CONTRAST Q111 CT HEA...,\nName: ___ Unit No: __...
4,335319,10000117,22927623.0,32642808,2181-11-14 21:51:00,2181-11-15 02:06:42,48,F,2174,NaN,...,141.0,77.0,0.0,0.0,1.0,NaN,NaN,10000117-RR-12,"CLINICAL HISTORY: Right upper quadrant pain, ...","CLINICAL HISTORY: Right upper quadrant pain, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242176,391557,19999733,27674281.0,30940569,2152-07-08 20:15:00,2152-07-09 03:45:00,19,F,2152,NaN,...,93.0,58.0,0.0,6.0,2.0,NaN,NaN,19999733-RR-2,"HISTORY: ___ woman, with memory problem, naus...","HISTORY: ___ woman, with memory problem, naus..."
242177,167404,19999784,26194817.0,35692999,2119-06-18 14:21:00,2119-06-18 21:09:29,57,M,2119,NaN,...,123.0,82.0,0.0,0.0,0.0,NaN,NaN,19999784-RR-13,EXAMINATION: VIDEO OROPHARYNGEAL SWALLOW\n\nI...,EXAMINATION: VIDEO OROPHARYNGEAL SWALLOW\n\nI...
242178,167405,19999784,24935234.0,37972930,2119-07-09 17:38:00,2119-07-10 00:04:00,57,M,2119,NaN,...,142.0,80.0,3.0,0.0,1.0,19999784-DS-7,\nName: ___ Unit No: __...,19999784-RR-23,EXAMINATION: MR ___ AND W/O CONTRAST ___ MR S...,\nName: ___ Unit No: __...
242179,167406,19999784,25715748.0,34149746,2119-08-11 09:15:00,2119-08-11 13:40:00,57,M,2119,NaN,...,131.0,92.0,0.0,1.0,8.0,19999784-DS-9,\nName: ___ Unit No: __...,19999784-RR-32,EXAMINATION: CT LUMBAR WANDW/O CONTRAST Q333 ...,\nName: ___ Unit No: __...
242180,167408,19999828,25744818.0,32917002,2149-01-08 09:11:00,2149-01-08 18:12:00,46,F,2147,NaN,...,111.0,78.0,4.0,8.0,11.0,19999828-DS-6,\nName: ___ Unit No: ___...,19999828-RR-22,EXAMINATION: CHEST (PORTABLE AP)\n\nINDICATIO...,\nName: ___ Unit No: ___...

In [29]:
# Check for conflicting hospitalization outcomes
conflict_hosp = (
    notes_df.groupby("notes")["outcome_hospitalization"]
    .nunique()
    .reset_index(name="n_unique")
)

conflict_hosp = conflict_hosp[conflict_hosp["n_unique"] > 1]

print("Notes with conflicting hospitalization outcomes:", len(conflict_hosp))


# Check for conflicting critical outcomes
conflict_crit = (
    notes_df.groupby("notes")["outcome_critical"]
    .nunique()
    .reset_index(name="n_unique")
)

conflict_crit = conflict_crit[conflict_crit["n_unique"] > 1]

print("Notes with conflicting critical outcomes:", len(conflict_crit))

Notes with conflicting hospitalization outcomes: 0
Notes with conflicting critical outcomes: 0

In [2]:
# !python clean_notes_mar6.py

clean_notes_mar9.py:62: DeprecationWarning: Flags not at the start of the expression '(?is)(?:^|\\n)\\s*(FIN' (truncated)
  RAD_FINDINGS_IMPRESSION_RE = re.compile(
clean_notes_mar9.py:79: DeprecationWarning: Flags not at the start of the expression '(?is)\\b(?:Discharge ' (truncated)
  DROP_RE = re.compile(
clean_notes_mar9.py:119: DeprecationWarning: Flags not at the start of the expression '(?is)(?:^|\\n)\\s*(?:C' (truncated)
  KEEP_BLOCK_RE = re.compile(
[chunk 1] loaded 10,000 rows in 1.5s
[chunk 2] loaded 10,000 rows in 1.0s
[chunk 3] loaded 10,000 rows in 1.0s
[chunk 4] loaded 10,000 rows in 1.6s
[chunk 5] loaded 10,000 rows in 1.1s
[chunk 6] loaded 10,000 rows in 1.1s
[chunk 7] loaded 10,000 rows in 2.5s
[chunk 8] loaded 10,000 rows in 2.3s
[chunk 9] loaded 10,000 rows in 2.3s
[chunk 10] loaded 10,000 rows in 2.4s
[chunk 11] loaded 10,000 rows in 2.1s
[chunk 12] loaded 10,000 rows in 1.0s
[chunk 13] loaded 10,000 rows in 1.1s
[chunk 14] loaded 10,000 rows in 1.8s
[chunk 15] loaded 10,000 rows in 1.1s
[chunk 16] loaded 10,000 rows in 1.0s
[chunk 17] loaded 10,000 rows in 1.0s
[chunk 18] loaded 10,000 rows in 1.0s
[chunk 19] loaded 10,000 rows in 2.2s
[chunk 20] loaded 10,000 rows in 1.0s
[chunk 21] loaded 10,000 rows in 1.0s
[chunk 22] loaded 10,000 rows in 1.0s
[chunk 23] loaded 10,000 rows in 1.8s
[chunk 24] loaded 10,000 rows in 1.4s
[chunk 25] loaded 2,181 rows in 0.3s
Cleaning: 242181rows [12:44, 316.92rows/s, last 2181 rows in 6.6s]

In [1]:
!python clean_notes_mar6_DISPOSITION.py

clean_notes_mar6_DISPOSITION.py:56: DeprecationWarning: Flags not at the start of the expression '(?is)\\b(?:Discharge ' (truncated)
  DROP_RE = re.compile(
clean_notes_mar6_DISPOSITION.py:77: DeprecationWarning: Flags not at the start of the expression '(?is)(?:^|\\n)\\s*(?:C' (truncated)
  KEEP_BLOCK_RE = re.compile(
[chunk 1] loaded 10,000 rows in 2.4s
[chunk 2] loaded 10,000 rows in 0.9s
[chunk 3] loaded 10,000 rows in 1.0s
[chunk 4] loaded 10,000 rows in 0.9s
[chunk 5] loaded 10,000 rows in 0.9s
[chunk 6] loaded 10,000 rows in 1.0s
[chunk 7] loaded 10,000 rows in 1.2s
[chunk 8] loaded 10,000 rows in 0.9s
[chunk 9] loaded 10,000 rows in 1.2s
[chunk 10] loaded 10,000 rows in 1.2s
[chunk 11] loaded 10,000 rows in 1.0s
[chunk 12] loaded 10,000 rows in 1.0s
[chunk 13] loaded 10,000 rows in 1.0s
[chunk 14] loaded 10,000 rows in 1.0s
[chunk 15] loaded 10,000 rows in 1.0s
[chunk 16] loaded 10,000 rows in 1.0s
[chunk 17] loaded 10,000 rows in 1.2s
[chunk 18] loaded 10,000 rows in 1.1s
[chunk 19] loaded 10,000 rows in 1.0s
[chunk 20] loaded 10,000 rows in 1.0s
[chunk 21] loaded 10,000 rows in 1.0s
[chunk 22] loaded 10,000 rows in 0.9s
[chunk 23] loaded 10,000 rows in 1.1s
[chunk 24] loaded 10,000 rows in 1.0s
[chunk 25] loaded 10,000 rows in 1.1s
[chunk 26] loaded 10,000 rows in 0.9s
[chunk 27] loaded 10,000 rows in 1.0s
[chunk 28] loaded 10,000 rows in 1.0s
[chunk 29] loaded 4,627 rows in 0.5s
Cleaning: 284627rows [09:15, 512.41rows/s, last 4627 rows in 8.5s]