In [1]:
import pandas as pd

In [2]:
structured_train = pd.read_csv('train.csv')
print(len(structured_train))
structured_test = pd.read_csv('test.csv')
print(len(structured_test))
print(len(structured_train) + len(structured_test))

359043
89761
448804

In [3]:
structured_train

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,ed_pain_last,n_med,n_medrecon,triage_MAP,score_CCI,score_CART,score_REMS,score_NEWS,score_NEWS2,score_MEWS
0,215414,18566742,27103162.0,38538786,2135-07-16 16:08:00,2135-07-17 01:49:00,58,F,2132,NaN,...,2.127651,5.0,2.0,97.333333,2,4,3,1,1,1
1,205452,16853729,NaN,30043998,2178-01-25 05:09:00,2178-01-25 07:05:00,91,F,2169,NaN,...,2.127651,2.0,3.0,118.333333,7,9,8,1,0,1
2,200705,16026698,NaN,39475313,2128-10-19 20:01:00,2128-10-19 20:16:00,23,M,2128,NaN,...,7.000000,1.0,1.0,116.000000,0,12,4,4,4,4
3,87038,15398519,25237915.0,35495155,2147-06-15 09:50:00,2147-06-15 15:55:00,57,M,2136,NaN,...,0.000000,7.0,10.0,100.000000,12,16,7,5,3,3
4,373626,16787687,23674090.0,31087259,2181-03-20 10:38:00,2181-03-21 12:55:00,87,F,2176,NaN,...,0.000000,6.0,13.0,87.000000,11,9,6,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359038,113182,10249080,NaN,32475431,2116-01-19 23:41:00,2116-01-19 23:55:00,29,M,2114,NaN,...,0.000000,0.0,0.0,98.666667,0,0,0,0,0,1
359039,323227,17819662,21020261.0,31105287,2182-02-08 00:32:00,2182-02-08 03:31:00,52,M,2182,NaN,...,2.127651,2.0,7.0,115.333333,1,0,4,0,0,1
359040,129321,13199993,24770260.0,37954239,2185-03-02 19:21:00,2185-03-04 15:48:00,37,M,2179,NaN,...,0.000000,7.0,0.0,116.666667,0,0,2,0,0,1
359041,167557,10028683,NaN,31802829,2171-12-05 17:36:00,2171-12-05 17:42:00,35,F,2169,NaN,...,0.000000,3.0,10.0,85.000000,1,0,0,0,0,1
359042,300451,13723460,25859289.0,39195476,2161-10-09 20:46:00,2161-10-10 01:26:00,87,M,2160,NaN,...,0.000000,3.0,0.0,96.622249,18,9,6,0,0,1

In [4]:
df_ecg = pd.read_csv("master_dataset_ecg_DISPOSITION.csv")
print(len(df_ecg))
df_ecg

220221

,level_0,visit_key,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,...,ed_heartrate_last,ed_resprate_last,ed_o2sat_last,ed_sbp_last,ed_dbp_last,ed_pain_last,n_med,n_medrecon,ecg_paths,last_ecg_path
0,3,335317,10000032,29079034.0,39399961,2180-07-23 05:54:00,2180-07-23 14:00:00,52,F,2180,...,96.0,18.0,97.0,86.0,45.0,NaN,8.0,14.0,['files/p1000/p10000032/s44458630/44458630'],files/p1000/p10000032/s44458630/44458630
1,4,335318,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,52,F,2180,...,91.0,18.0,99.0,98.0,60.0,NaN,6.0,7.0,['files/p1000/p10000032/s40689238/40689238'],files/p1000/p10000032/s40689238/40689238
2,12,335319,10000117,22927623.0,32642808,2181-11-14 21:51:00,2181-11-15 02:06:42,48,F,2174,...,85.0,21.0,98.0,141.0,77.0,0.0,0.0,1.0,['files/p1000/p10000117/s45090959/45090959'],files/p1000/p10000117/s45090959/45090959
3,14,335321,10000117,27988844.0,33176849,2183-09-18 08:41:00,2183-09-18 20:20:00,48,F,2174,...,88.0,18.0,95.0,112.0,72.0,0.0,0.0,0.0,['files/p1000/p10000117/s48446569/48446569'],files/p1000/p10000117/s48446569/48446569
4,17,279332,10000285,NaN,37909301,2159-11-26 14:22:00,2159-11-26 14:44:00,34,M,2159,...,66.0,14.0,100.0,136.0,92.0,1.0,1.0,0.0,['files/p1000/p10000285/s42709053/42709053'],files/p1000/p10000285/s42709053/42709053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220216,448963,391557,19999733,27674281.0,30940569,2152-07-08 20:15:00,2152-07-09 03:45:00,19,F,2152,...,54.0,16.0,100.0,93.0,58.0,0.0,6.0,2.0,['files/p1999/p19999733/s42489677/42489677'],files/p1999/p19999733/s42489677/42489677
220217,448965,167404,19999784,26194817.0,35692999,2119-06-18 14:21:00,2119-06-18 21:09:29,57,M,2119,...,75.0,16.0,99.0,123.0,82.0,0.0,0.0,0.0,['files/p1999/p19999784/s40734999/40734999'],files/p1999/p19999784/s40734999/40734999
220218,448967,167406,19999784,25715748.0,34149746,2119-08-11 09:15:00,2119-08-11 13:40:00,57,M,2119,...,72.0,16.0,100.0,131.0,92.0,0.0,1.0,8.0,['files/p1999/p19999784/s47639679/47639679'],files/p1999/p19999784/s47639679/47639679
220219,448969,167408,19999828,25744818.0,32917002,2149-01-08 09:11:00,2149-01-08 18:12:00,46,F,2147,...,109.0,15.0,96.0,111.0,78.0,4.0,8.0,11.0,['files/p1999/p19999828/s40643529/40643529'],files/p1999/p19999828/s40643529/40643529
220220,448971,335313,19999987,23865745.0,34731548,2145-11-02 19:28:00,2145-11-02 22:59:00,57,F,2145,...,103.0,20.0,NaN,113.0,79.0,NaN,4.0,0.0,['files/p1999/p19999987/s41190887/41190887'],files/p1999/p19999987/s41190887/41190887

In [5]:
import pandas as pd
import ast

df = df_ecg

df["ecg_paths"] = df["ecg_paths"].apply(ast.literal_eval)

df["last_ecg_path"] = df["ecg_paths"].apply(lambda x: x[-1] if isinstance(x, list) and len(x) > 0 else None)

g = df.groupby(["subject_id", "last_ecg_path"])

conflicts = g.filter(
    lambda x: (
        x["outcome_critical"].nunique() > 1
        or x["outcome_hospitalization"].nunique() > 1
    )
)

conflicts

Empty DataFrame
Columns: [level_0, visit_key, subject_id, hadm_id, stay_id, intime, outtime, anchor_age, gender, anchor_year, dod, admittime, dischtime, deathtime, ethnicity, edregtime, edouttime, insurance, in_year, age, outcome_inhospital_mortality, ed_death, before_ed_mortality, ed_los, intime_icu, time_to_icu_transfer, outcome_icu_transfer_12h, outcome_hospitalization, outcome_critical, n_ed_30d, n_ed_90d, n_ed_365d, next_ed_visit_time, next_ed_visit_time_diff, outcome_ed_revisit_3d, n_hosp_30d, n_hosp_90d, n_hosp_365d, n_icu_30d, n_icu_90d, n_icu_365d, ed_los_hours, time_to_icu_transfer_hours, next_ed_visit_time_diff_days, triage_temperature, triage_heartrate, triage_resprate, triage_o2sat, triage_sbp, triage_dbp, triage_pain, triage_acuity, chiefcomplaint, chiefcom_chest_pain, chiefcom_abdominal_pain, chiefcom_headache, chiefcom_shortness_of_breath, chiefcom_back_pain, chiefcom_cough, chiefcom_nausea_vomiting, chiefcom_fever_chills, chiefcom_syncope, chiefcom_dizziness, cci_MI, cci_CHF, cci_PVD, cci_Stroke, cci_Dementia, cci_Pulmonary, cci_Rheumatic, cci_PUD, cci_Liver1, cci_DM1, cci_DM2, cci_Paralysis, cci_Renal, cci_Cancer1, cci_Liver2, cci_Cancer2, cci_HIV, eci_CHF, eci_Arrhythmia, eci_Valvular, eci_PHTN, eci_PVD, eci_HTN1, eci_HTN2, eci_Paralysis, eci_NeuroOther, eci_Pulmonary, eci_DM1, eci_DM2, eci_Hypothyroid, eci_Renal, eci_Liver, eci_PUD, eci_HIV, eci_Lymphoma, eci_Tumor2, eci_Tumor1, ...]
Index: []

[0 rows x 122 columns]

In [6]:
df_notes = pd.read_csv("master_dataset_notes_cleaned_DISPOSITION.csv")
print(len(df_notes))
df_notes

284627

,index,subject_id,stay_id,notes,outcome_hospitalization,outcome_critical
0,335314,10000032,33258284,examination liver or gallbladder us single org...,True,False
1,335315,10000032,38112554,worsening abd distension and pain hcv cirrhosi...,True,False
2,335316,10000032,32952584,abdominal fullness and discomfort with hiv on ...,True,True
3,335317,10000032,39399961,examination chest portable ap indication with ...,True,True
4,335318,10000032,35968195,altered mental status mrs is a female with hiv...,True,False
...,...,...,...,...,...,...
284622,167405,19999784,37972930,lle weakness dysphagia is a year old right han...,True,False
284623,167406,19999784,34149746,intramedullary spinal cord lesion at the conus...,True,False
284624,167407,19999828,30712109,indication year old woman with new right 41cm ...,True,False
284625,167408,19999828,32917002,ms on anticoagulation diverticulosis htn copd ...,True,True
284626,335313,19999987,34731548,history with left occipital bleeding assess fo...,True,True

In [7]:
df_notes.columns.to_list()

['index',
 'subject_id',
 'stay_id',
 'notes',
 'outcome_hospitalization',
 'outcome_critical']

In [8]:
conflict_hosp_notes = (
    df_notes.groupby("notes")["outcome_hospitalization"]
    .nunique()
    .loc[lambda x: x > 1]
    .index
)

# find notes with conflicting critical outcomes
conflict_crit_notes = (
    df_notes.groupby("notes")["outcome_critical"]
    .nunique()
    .loc[lambda x: x > 1]
    .index
)

# combine both sets
conflict_notes = set(conflict_hosp_notes).union(set(conflict_crit_notes))

print("Total conflicting note texts:", len(conflict_notes))

# remove them
df_notes_clean = df_notes[~df_notes["notes"].isin(conflict_notes)].copy()

print("Rows before:", len(df_notes))
print("Rows after:", len(df_notes_clean))

Total conflicting note texts: 56
Rows before: 284627
Rows after: 284481

In [9]:
df_notes

,index,subject_id,stay_id,notes,outcome_hospitalization,outcome_critical
0,335314,10000032,33258284,examination liver or gallbladder us single org...,True,False
1,335315,10000032,38112554,worsening abd distension and pain hcv cirrhosi...,True,False
2,335316,10000032,32952584,abdominal fullness and discomfort with hiv on ...,True,True
3,335317,10000032,39399961,examination chest portable ap indication with ...,True,True
4,335318,10000032,35968195,altered mental status mrs is a female with hiv...,True,False
...,...,...,...,...,...,...
284622,167405,19999784,37972930,lle weakness dysphagia is a year old right han...,True,False
284623,167406,19999784,34149746,intramedullary spinal cord lesion at the conus...,True,False
284624,167407,19999828,30712109,indication year old woman with new right 41cm ...,True,False
284625,167408,19999828,32917002,ms on anticoagulation diverticulosis htn copd ...,True,True
284626,335313,19999987,34731548,history with left occipital bleeding assess fo...,True,True

In [10]:
df_ecg

,level_0,visit_key,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,...,ed_heartrate_last,ed_resprate_last,ed_o2sat_last,ed_sbp_last,ed_dbp_last,ed_pain_last,n_med,n_medrecon,ecg_paths,last_ecg_path
0,3,335317,10000032,29079034.0,39399961,2180-07-23 05:54:00,2180-07-23 14:00:00,52,F,2180,...,96.0,18.0,97.0,86.0,45.0,NaN,8.0,14.0,[files/p1000/p10000032/s44458630/44458630],files/p1000/p10000032/s44458630/44458630
1,4,335318,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,52,F,2180,...,91.0,18.0,99.0,98.0,60.0,NaN,6.0,7.0,[files/p1000/p10000032/s40689238/40689238],files/p1000/p10000032/s40689238/40689238
2,12,335319,10000117,22927623.0,32642808,2181-11-14 21:51:00,2181-11-15 02:06:42,48,F,2174,...,85.0,21.0,98.0,141.0,77.0,0.0,0.0,1.0,[files/p1000/p10000117/s45090959/45090959],files/p1000/p10000117/s45090959/45090959
3,14,335321,10000117,27988844.0,33176849,2183-09-18 08:41:00,2183-09-18 20:20:00,48,F,2174,...,88.0,18.0,95.0,112.0,72.0,0.0,0.0,0.0,[files/p1000/p10000117/s48446569/48446569],files/p1000/p10000117/s48446569/48446569
4,17,279332,10000285,NaN,37909301,2159-11-26 14:22:00,2159-11-26 14:44:00,34,M,2159,...,66.0,14.0,100.0,136.0,92.0,1.0,1.0,0.0,[files/p1000/p10000285/s42709053/42709053],files/p1000/p10000285/s42709053/42709053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220216,448963,391557,19999733,27674281.0,30940569,2152-07-08 20:15:00,2152-07-09 03:45:00,19,F,2152,...,54.0,16.0,100.0,93.0,58.0,0.0,6.0,2.0,[files/p1999/p19999733/s42489677/42489677],files/p1999/p19999733/s42489677/42489677
220217,448965,167404,19999784,26194817.0,35692999,2119-06-18 14:21:00,2119-06-18 21:09:29,57,M,2119,...,75.0,16.0,99.0,123.0,82.0,0.0,0.0,0.0,[files/p1999/p19999784/s40734999/40734999],files/p1999/p19999784/s40734999/40734999
220218,448967,167406,19999784,25715748.0,34149746,2119-08-11 09:15:00,2119-08-11 13:40:00,57,M,2119,...,72.0,16.0,100.0,131.0,92.0,0.0,1.0,8.0,[files/p1999/p19999784/s47639679/47639679],files/p1999/p19999784/s47639679/47639679
220219,448969,167408,19999828,25744818.0,32917002,2149-01-08 09:11:00,2149-01-08 18:12:00,46,F,2147,...,109.0,15.0,96.0,111.0,78.0,4.0,8.0,11.0,[files/p1999/p19999828/s40643529/40643529],files/p1999/p19999828/s40643529/40643529
220220,448971,335313,19999987,23865745.0,34731548,2145-11-02 19:28:00,2145-11-02 22:59:00,57,F,2145,...,103.0,20.0,NaN,113.0,79.0,NaN,4.0,0.0,[files/p1999/p19999987/s41190887/41190887],files/p1999/p19999987/s41190887/41190887

In [11]:
structured_train

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,ed_pain_last,n_med,n_medrecon,triage_MAP,score_CCI,score_CART,score_REMS,score_NEWS,score_NEWS2,score_MEWS
0,215414,18566742,27103162.0,38538786,2135-07-16 16:08:00,2135-07-17 01:49:00,58,F,2132,NaN,...,2.127651,5.0,2.0,97.333333,2,4,3,1,1,1
1,205452,16853729,NaN,30043998,2178-01-25 05:09:00,2178-01-25 07:05:00,91,F,2169,NaN,...,2.127651,2.0,3.0,118.333333,7,9,8,1,0,1
2,200705,16026698,NaN,39475313,2128-10-19 20:01:00,2128-10-19 20:16:00,23,M,2128,NaN,...,7.000000,1.0,1.0,116.000000,0,12,4,4,4,4
3,87038,15398519,25237915.0,35495155,2147-06-15 09:50:00,2147-06-15 15:55:00,57,M,2136,NaN,...,0.000000,7.0,10.0,100.000000,12,16,7,5,3,3
4,373626,16787687,23674090.0,31087259,2181-03-20 10:38:00,2181-03-21 12:55:00,87,F,2176,NaN,...,0.000000,6.0,13.0,87.000000,11,9,6,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359038,113182,10249080,NaN,32475431,2116-01-19 23:41:00,2116-01-19 23:55:00,29,M,2114,NaN,...,0.000000,0.0,0.0,98.666667,0,0,0,0,0,1
359039,323227,17819662,21020261.0,31105287,2182-02-08 00:32:00,2182-02-08 03:31:00,52,M,2182,NaN,...,2.127651,2.0,7.0,115.333333,1,0,4,0,0,1
359040,129321,13199993,24770260.0,37954239,2185-03-02 19:21:00,2185-03-04 15:48:00,37,M,2179,NaN,...,0.000000,7.0,0.0,116.666667,0,0,2,0,0,1
359041,167557,10028683,NaN,31802829,2171-12-05 17:36:00,2171-12-05 17:42:00,35,F,2169,NaN,...,0.000000,3.0,10.0,85.000000,1,0,0,0,0,1
359042,300451,13723460,25859289.0,39195476,2161-10-09 20:46:00,2161-10-10 01:26:00,87,M,2160,NaN,...,0.000000,3.0,0.0,96.622249,18,9,6,0,0,1

In [12]:
structured_test

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,ed_pain_last,n_med,n_medrecon,triage_MAP,score_CCI,score_CART,score_REMS,score_NEWS,score_NEWS2,score_MEWS
0,335316,10000032,29079034.0,32952584,2180-07-22 16:24:00,2180-07-23 05:54:00,52,F,2180,NaN,...,0.000000,2.0,14.0,52.333333,6,4,4,3,3,2
1,56672,10000084,29888819.0,36954971,2160-12-27 18:32:00,2160-12-28 16:07:00,72,M,2160,NaN,...,0.000000,1.0,6.0,85.000000,4,9,5,1,0,1
2,0,10000115,NaN,38081480,2154-12-10 02:04:00,2154-12-10 02:16:00,24,M,2154,NaN,...,0.000000,0.0,0.0,87.333333,0,0,0,0,0,1
3,335319,10000117,22927623.0,32642808,2181-11-14 21:51:00,2181-11-15 02:06:42,48,F,2174,NaN,...,0.000000,0.0,1.0,104.666667,1,4,3,0,0,1
4,335320,10000117,NaN,30632130,2183-07-17 10:30:00,2183-07-17 10:40:00,48,F,2174,NaN,...,0.000000,0.0,0.0,70.000000,1,8,5,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89756,223462,19999156,22917423.0,39012698,2123-01-27 13:13:00,2123-01-27 21:39:00,62,F,2123,NaN,...,0.000000,1.0,1.0,104.333333,2,4,3,0,0,1
89757,111942,19999175,NaN,34469189,2185-08-13 20:35:00,2185-08-13 22:24:00,21,M,2185,NaN,...,2.127651,0.0,0.0,93.000000,0,0,2,0,0,1
89758,448969,19999270,NaN,30502357,2184-02-11 21:11:00,2184-02-11 21:14:00,33,M,2184,NaN,...,0.000000,0.0,0.0,71.000000,0,4,0,1,1,1
89759,56670,19999466,21397174.0,30402875,2116-08-30 12:11:00,2116-08-31 21:49:00,33,M,2116,NaN,...,0.000000,3.0,0.0,134.333333,0,0,3,0,0,1
89760,167407,19999828,29734428.0,30712109,2147-07-17 17:18:00,2147-07-18 17:34:00,46,F,2147,NaN,...,9.000000,11.0,8.0,85.666667,0,0,2,1,1,1

In [13]:
structured_train["split"] = "train"
structured_test["split"] = "test"

structured_full = pd.concat([structured_train, structured_test], ignore_index=True)

In [14]:
structured_full

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,n_med,n_medrecon,triage_MAP,score_CCI,score_CART,score_REMS,score_NEWS,score_NEWS2,score_MEWS,split
0,215414,18566742,27103162.0,38538786,2135-07-16 16:08:00,2135-07-17 01:49:00,58,F,2132,NaN,...,5.0,2.0,97.333333,2,4,3,1,1,1,train
1,205452,16853729,NaN,30043998,2178-01-25 05:09:00,2178-01-25 07:05:00,91,F,2169,NaN,...,2.0,3.0,118.333333,7,9,8,1,0,1,train
2,200705,16026698,NaN,39475313,2128-10-19 20:01:00,2128-10-19 20:16:00,23,M,2128,NaN,...,1.0,1.0,116.000000,0,12,4,4,4,4,train
3,87038,15398519,25237915.0,35495155,2147-06-15 09:50:00,2147-06-15 15:55:00,57,M,2136,NaN,...,7.0,10.0,100.000000,12,16,7,5,3,3,train
4,373626,16787687,23674090.0,31087259,2181-03-20 10:38:00,2181-03-21 12:55:00,87,F,2176,NaN,...,6.0,13.0,87.000000,11,9,6,0,0,0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448799,223462,19999156,22917423.0,39012698,2123-01-27 13:13:00,2123-01-27 21:39:00,62,F,2123,NaN,...,1.0,1.0,104.333333,2,4,3,0,0,1,test
448800,111942,19999175,NaN,34469189,2185-08-13 20:35:00,2185-08-13 22:24:00,21,M,2185,NaN,...,0.0,0.0,93.000000,0,0,2,0,0,1,test
448801,448969,19999270,NaN,30502357,2184-02-11 21:11:00,2184-02-11 21:14:00,33,M,2184,NaN,...,0.0,0.0,71.000000,0,4,0,1,1,1,test
448802,56670,19999466,21397174.0,30402875,2116-08-30 12:11:00,2116-08-31 21:49:00,33,M,2116,NaN,...,3.0,0.0,134.333333,0,0,3,0,0,1,test
448803,167407,19999828,29734428.0,30712109,2147-07-17 17:18:00,2147-07-18 17:34:00,46,F,2147,NaN,...,11.0,8.0,85.666667,0,0,2,1,1,1,test

In [15]:
len(structured_full)

448804

In [16]:
structured_full["stay_id"].nunique()

448804

In [17]:
structured_full = structured_full.merge(
    df_notes[["stay_id", "notes"]],
    on="stay_id",
    how="left"
)

structured_full = structured_full.merge(
    df_ecg[["stay_id", "ecg_paths"]],
    on="stay_id",
    how="left"
)

In [18]:
structured_full

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,triage_MAP,score_CCI,score_CART,score_REMS,score_NEWS,score_NEWS2,score_MEWS,split,notes,ecg_paths
0,215414,18566742,27103162.0,38538786,2135-07-16 16:08:00,2135-07-17 01:49:00,58,F,2132,NaN,...,97.333333,2,4,3,1,1,1,train,NaN,NaN
1,205452,16853729,NaN,30043998,2178-01-25 05:09:00,2178-01-25 07:05:00,91,F,2169,NaN,...,118.333333,7,9,8,1,0,1,train,examination chest radiograph indication woman ...,[files/p1685/p16853729/s43126841/43126841]
2,200705,16026698,NaN,39475313,2128-10-19 20:01:00,2128-10-19 20:16:00,23,M,2128,NaN,...,116.000000,0,12,4,4,4,4,train,indication with left arm pain after mva eval f...,NaN
3,87038,15398519,25237915.0,35495155,2147-06-15 09:50:00,2147-06-15 15:55:00,57,M,2136,NaN,...,100.000000,12,16,7,5,3,3,train,year old man with a history of severe copd not...,[files/p1539/p15398519/s48889255/48889255]
4,373626,16787687,23674090.0,31087259,2181-03-20 10:38:00,2181-03-21 12:55:00,87,F,2176,NaN,...,87.000000,11,9,6,0,0,0,train,examination mr spine w o contrast mr spine ind...,[files/p1678/p16787687/s45350570/45350570]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448799,223462,19999156,22917423.0,39012698,2123-01-27 13:13:00,2123-01-27 21:39:00,62,F,2123,NaN,...,104.333333,2,4,3,0,0,1,test,chest two views history female with left sided...,[files/p1999/p19999156/s44234204/44234204]
448800,111942,19999175,NaN,34469189,2185-08-13 20:35:00,2185-08-13 22:24:00,21,M,2185,NaN,...,93.000000,0,0,2,0,0,1,test,history right hand pain and for punching anoth...,NaN
448801,448969,19999270,NaN,30502357,2184-02-11 21:11:00,2184-02-11 21:14:00,33,M,2184,NaN,...,71.000000,0,4,0,1,1,1,test,NaN,NaN
448802,56670,19999466,21397174.0,30402875,2116-08-30 12:11:00,2116-08-31 21:49:00,33,M,2116,NaN,...,134.333333,0,0,3,0,0,1,test,NaN,NaN
448803,167407,19999828,29734428.0,30712109,2147-07-17 17:18:00,2147-07-18 17:34:00,46,F,2147,NaN,...,85.666667,0,0,2,1,1,1,test,indication year old woman with new right 41cm ...,NaN

In [19]:
structured_full = structured_full[
    structured_full["notes"].notna() & structured_full["ecg_paths"].notna()
]

In [20]:
len(structured_full)

189858

In [21]:
structured_full["subject_id"].nunique()

80536

In [22]:
print(structured_full["outcome_hospitalization"].value_counts())

outcome_hospitalization
True     128335
False     61523
Name: count, dtype: int64

In [23]:
# shuffle rows
structured_full = structured_full.sample(frac=1, random_state=3180).reset_index(drop=True)

n = len(structured_full)

train_end = int(0.8 * n)
val_end = int(0.9 * n)

train_df = structured_full.iloc[:train_end]
val_df   = structured_full.iloc[train_end:val_end]
test_df  = structured_full.iloc[val_end:]

In [24]:
train_df.to_csv("mv_train_DISPOSITION.csv", index=False)
val_df.to_csv("mv_val_DISPOSITION.csv", index=False)
test_df.to_csv("mv_test_DISPOSITION.csv", index=False)

In [25]:
len(test_df)

18986

In [26]:
len(val_df)

18986

In [27]:
train_df

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,triage_MAP,score_CCI,score_CART,score_REMS,score_NEWS,score_NEWS2,score_MEWS,split,notes,ecg_paths
0,17625,13109623,NaN,34225339,2140-04-07 14:05:00,2140-04-07 14:24:00,63,F,2137,NaN,...,90.000000,4,4,7,0,0,1,train,female with pmhx of copd presents with worseni...,[files/p1310/p13109623/s42270583/42270583]
1,2551,10455855,28782492.0,39040844,2173-05-23 15:30:00,2173-05-24 14:15:00,83,F,2168,NaN,...,93.333333,13,9,6,0,0,1,train,hx dm cad dddr pacer htn pvd ckd and other med...,[files/p1045/p10455855/s42219625/42219625]
2,206075,16957065,20359481.0,31366838,2141-05-15 12:48:00,2141-05-15 14:33:48,45,M,2141,NaN,...,96.622249,0,0,2,0,0,1,train,exam chest single ap upright portable view cli...,[files/p1695/p16957065/s42159886/42159886]
3,286106,11250014,28672115.0,33227506,2153-12-15 19:16:00,2153-12-16 02:45:00,66,M,2153,NaN,...,99.666667,2,4,5,1,0,1,train,examination pelvis w judet views 3v indication...,[files/p1125/p11250014/s40838501/40838501]
4,175768,11575157,23296236.0,34870767,2209-06-01 15:54:00,2209-06-02 03:26:00,63,F,2201,NaN,...,162.000000,8,35,16,8,5,5,train,yo f with hx severe copd on home oxygen 2 l s ...,[files/p1157/p11575157/s42678981/42678981]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151881,70976,12515782,21618233.0,35330710,2178-06-01 14:48:00,2178-06-01 20:21:00,57,M,2177,NaN,...,107.666667,1,4,3,1,1,1,test,with pmh of alcohol abuse withdrawal seizures ...,[files/p1251/p12515782/s49391930/49391930]
151882,396036,10751923,22587031.0,33110185,2196-09-19 17:40:00,2196-09-20 03:51:00,41,F,2189,NaN,...,69.666667,12,0,2,4,4,3,train,indication with hx of hiv presenting with hypo...,[files/p1075/p10751923/s49535008/49535008]
151883,315682,16474068,NaN,38253971,2180-05-04 14:07:00,2180-05-04 14:15:00,76,M,2175,NaN,...,95.333333,4,9,8,0,0,1,train,examination oropharyngeal video swallow indica...,[files/p1647/p16474068/s46352924/46352924]
151884,19947,13496539,29123414.0,38580514,2201-09-10 14:05:00,2201-09-10 22:16:00,91,F,2200,NaN,...,84.000000,5,9,9,2,2,2,train,altered mental status with h o bradycardia div...,[files/p1349/p13496539/s49427037/49427037]
151885,383314,18520284,NaN,36742604,2154-02-18 20:04:00,2154-02-18 20:28:00,68,F,2154,NaN,...,94.000000,2,4,5,0,0,1,train,examination bilateral digital 2d screening mam...,[files/p1852/p18520284/s49323611/49323611]