In [1]:
import pandas as pd

In [2]:
structured_train = pd.read_csv('train.csv')
print(len(structured_train))
structured_test = pd.read_csv('test.csv')
print(len(structured_test))
print(len(structured_train) + len(structured_test))

359043
89761
448804

In [3]:
structured_train

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,ed_pain_last,n_med,n_medrecon,triage_MAP,score_CCI,score_CART,score_REMS,score_NEWS,score_NEWS2,score_MEWS
0,215414,18566742,27103162.0,38538786,2135-07-16 16:08:00,2135-07-17 01:49:00,58,F,2132,NaN,...,2.127651,5.0,2.0,97.333333,2,4,3,1,1,1
1,205452,16853729,NaN,30043998,2178-01-25 05:09:00,2178-01-25 07:05:00,91,F,2169,NaN,...,2.127651,2.0,3.0,118.333333,7,9,8,1,0,1
2,200705,16026698,NaN,39475313,2128-10-19 20:01:00,2128-10-19 20:16:00,23,M,2128,NaN,...,7.000000,1.0,1.0,116.000000,0,12,4,4,4,4
3,87038,15398519,25237915.0,35495155,2147-06-15 09:50:00,2147-06-15 15:55:00,57,M,2136,NaN,...,0.000000,7.0,10.0,100.000000,12,16,7,5,3,3
4,373626,16787687,23674090.0,31087259,2181-03-20 10:38:00,2181-03-21 12:55:00,87,F,2176,NaN,...,0.000000,6.0,13.0,87.000000,11,9,6,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359038,113182,10249080,NaN,32475431,2116-01-19 23:41:00,2116-01-19 23:55:00,29,M,2114,NaN,...,0.000000,0.0,0.0,98.666667,0,0,0,0,0,1
359039,323227,17819662,21020261.0,31105287,2182-02-08 00:32:00,2182-02-08 03:31:00,52,M,2182,NaN,...,2.127651,2.0,7.0,115.333333,1,0,4,0,0,1
359040,129321,13199993,24770260.0,37954239,2185-03-02 19:21:00,2185-03-04 15:48:00,37,M,2179,NaN,...,0.000000,7.0,0.0,116.666667,0,0,2,0,0,1
359041,167557,10028683,NaN,31802829,2171-12-05 17:36:00,2171-12-05 17:42:00,35,F,2169,NaN,...,0.000000,3.0,10.0,85.000000,1,0,0,0,0,1
359042,300451,13723460,25859289.0,39195476,2161-10-09 20:46:00,2161-10-10 01:26:00,87,M,2160,NaN,...,0.000000,3.0,0.0,96.622249,18,9,6,0,0,1

In [6]:
df_ecg = pd.read_csv("master_dataset_ecg_NEW_v3.csv")
print(len(df_ecg))
df_ecg

185378

,level_0,visit_key,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,...,ed_heartrate_last,ed_resprate_last,ed_o2sat_last,ed_sbp_last,ed_dbp_last,ed_pain_last,n_med,n_medrecon,ecg_paths,last_ecg_path
0,4,335318,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,52,F,2180,...,91.0,18.0,99.0,98.0,60.0,NaN,6.0,7.0,['files/p1000/p10000032/s44458630/44458630'],files/p1000/p10000032/s44458630/44458630
1,12,335319,10000117,22927623.0,32642808,2181-11-14 21:51:00,2181-11-15 02:06:42,48,F,2174,...,85.0,21.0,98.0,141.0,77.0,0.0,0.0,1.0,['files/p1000/p10000117/s45090959/45090959'],files/p1000/p10000117/s45090959/45090959
2,18,279333,10000285,NaN,36555703,2161-11-08 14:19:00,2161-11-08 14:24:00,34,M,2159,...,82.0,16.0,96.0,123.0,80.0,5.0,5.0,0.0,['files/p1000/p10000285/s42709053/42709053'],files/p1000/p10000285/s42709053/42709053
3,23,111945,10000635,NaN,31767754,2138-09-29 10:54:00,2138-09-29 11:05:00,74,F,2136,...,55.0,16.0,100.0,122.0,70.0,0.0,1.0,5.0,['files/p1000/p10000635/s43522917/43522917'],files/p1000/p10000635/s43522917/43522917
4,24,111946,10000635,NaN,38135254,2141-08-15 11:32:00,2141-08-15 11:41:00,74,F,2136,...,58.0,17.0,100.0,122.0,65.0,0.0,1.0,6.0,['files/p1000/p10000635/s42947358/42947358'],files/p1000/p10000635/s42947358/42947358
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185373,448959,279330,19999442,NaN,30337261,2149-09-07 18:19:00,2149-09-07 18:26:00,41,M,2146,...,74.0,16.0,100.0,120.0,82.0,0.0,4.0,2.0,['files/p1999/p19999442/s49466572/49466572'],files/p1999/p19999442/s49466572/49466572
185374,448960,56669,19999464,23033573.0,34571984,2171-08-01 15:12:00,2171-08-01 19:31:00,35,F,2160,...,58.0,16.0,100.0,100.0,64.0,8.0,4.0,8.0,['files/p1999/p19999464/s44488939/44488939'],files/p1999/p19999464/s44488939/44488939
185375,448966,167405,19999784,24935234.0,37972930,2119-07-09 17:38:00,2119-07-10 00:04:00,57,M,2119,...,76.0,16.0,99.0,142.0,80.0,3.0,0.0,1.0,['files/p1999/p19999784/s40734999/40734999'],files/p1999/p19999784/s40734999/40734999
185376,448967,167406,19999784,25715748.0,34149746,2119-08-11 09:15:00,2119-08-11 13:40:00,57,M,2119,...,72.0,16.0,100.0,131.0,92.0,0.0,1.0,8.0,['files/p1999/p19999784/s47639679/47639679'],files/p1999/p19999784/s47639679/47639679
185377,448969,167408,19999828,25744818.0,32917002,2149-01-08 09:11:00,2149-01-08 18:12:00,46,F,2147,...,109.0,15.0,96.0,111.0,78.0,4.0,8.0,11.0,['files/p1999/p19999828/s40643529/40643529'],files/p1999/p19999828/s40643529/40643529

In [8]:
df_notes = pd.read_csv("master_dataset_notes_cleaned_HOSPRED_ULTRA_256TOK_v3.csv")
print(len(df_notes))
df_notes

242181

,index,subject_id,stay_id,notes,outcome_hospitalization,outcome_critical
0,335315,10000032,38112554,worsening abd distension and pain hcv cirrhosi...,True,False
1,335316,10000032,32952584,abdominal fullness and discomfort with hiv on ...,True,True
2,335318,10000032,35968195,altered mental status is a female with hiv on ...,True,False
3,56672,10000084,36954971,male with disease dyslipidemia and a history o...,True,False
4,335319,10000117,32642808,clinical history right upper quadrant pain eva...,True,False
...,...,...,...,...,...,...
242176,391557,19999733,30940569,history woman with memory problem nausea heada...,True,False
242177,167404,19999784,35692999,obstruction with modified barium swallow pendi...,True,False
242178,167405,19999784,37972930,lle weakness dysphagia is a year old right han...,True,False
242179,167406,19999784,34149746,intramedullary spinal cord lesion at the conus...,True,False
242180,167408,19999828,32917002,enterocutaneous enteroatmospheric fistula is a...,True,True

In [9]:
df_notes.columns.to_list()

['index',
 'subject_id',
 'stay_id',
 'notes',
 'outcome_hospitalization',
 'outcome_critical']

In [10]:
conflict_hosp_notes = (
    df_notes.groupby("notes")["outcome_hospitalization"]
    .nunique()
    .loc[lambda x: x > 1]
    .index
)

# find notes with conflicting critical outcomes
conflict_crit_notes = (
    df_notes.groupby("notes")["outcome_critical"]
    .nunique()
    .loc[lambda x: x > 1]
    .index
)

# combine both sets
conflict_notes = set(conflict_hosp_notes).union(set(conflict_crit_notes))

print("Total conflicting note texts:", len(conflict_notes))

# remove them
df_notes_clean = df_notes[~df_notes["notes"].isin(conflict_notes)].copy()

print("Rows before:", len(df_notes))
print("Rows after:", len(df_notes_clean))

Total conflicting note texts: 575
Rows before: 242181
Rows after: 237933

In [11]:
df_notes

,index,subject_id,stay_id,notes,outcome_hospitalization,outcome_critical
0,335315,10000032,38112554,worsening abd distension and pain hcv cirrhosi...,True,False
1,335316,10000032,32952584,abdominal fullness and discomfort with hiv on ...,True,True
2,335318,10000032,35968195,altered mental status is a female with hiv on ...,True,False
3,56672,10000084,36954971,male with disease dyslipidemia and a history o...,True,False
4,335319,10000117,32642808,clinical history right upper quadrant pain eva...,True,False
...,...,...,...,...,...,...
242176,391557,19999733,30940569,history woman with memory problem nausea heada...,True,False
242177,167404,19999784,35692999,obstruction with modified barium swallow pendi...,True,False
242178,167405,19999784,37972930,lle weakness dysphagia is a year old right han...,True,False
242179,167406,19999784,34149746,intramedullary spinal cord lesion at the conus...,True,False
242180,167408,19999828,32917002,enterocutaneous enteroatmospheric fistula is a...,True,True

In [12]:
df_ecg

,level_0,visit_key,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,...,ed_heartrate_last,ed_resprate_last,ed_o2sat_last,ed_sbp_last,ed_dbp_last,ed_pain_last,n_med,n_medrecon,ecg_paths,last_ecg_path
0,4,335318,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,52,F,2180,...,91.0,18.0,99.0,98.0,60.0,NaN,6.0,7.0,['files/p1000/p10000032/s44458630/44458630'],files/p1000/p10000032/s44458630/44458630
1,12,335319,10000117,22927623.0,32642808,2181-11-14 21:51:00,2181-11-15 02:06:42,48,F,2174,...,85.0,21.0,98.0,141.0,77.0,0.0,0.0,1.0,['files/p1000/p10000117/s45090959/45090959'],files/p1000/p10000117/s45090959/45090959
2,18,279333,10000285,NaN,36555703,2161-11-08 14:19:00,2161-11-08 14:24:00,34,M,2159,...,82.0,16.0,96.0,123.0,80.0,5.0,5.0,0.0,['files/p1000/p10000285/s42709053/42709053'],files/p1000/p10000285/s42709053/42709053
3,23,111945,10000635,NaN,31767754,2138-09-29 10:54:00,2138-09-29 11:05:00,74,F,2136,...,55.0,16.0,100.0,122.0,70.0,0.0,1.0,5.0,['files/p1000/p10000635/s43522917/43522917'],files/p1000/p10000635/s43522917/43522917
4,24,111946,10000635,NaN,38135254,2141-08-15 11:32:00,2141-08-15 11:41:00,74,F,2136,...,58.0,17.0,100.0,122.0,65.0,0.0,1.0,6.0,['files/p1000/p10000635/s42947358/42947358'],files/p1000/p10000635/s42947358/42947358
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185373,448959,279330,19999442,NaN,30337261,2149-09-07 18:19:00,2149-09-07 18:26:00,41,M,2146,...,74.0,16.0,100.0,120.0,82.0,0.0,4.0,2.0,['files/p1999/p19999442/s49466572/49466572'],files/p1999/p19999442/s49466572/49466572
185374,448960,56669,19999464,23033573.0,34571984,2171-08-01 15:12:00,2171-08-01 19:31:00,35,F,2160,...,58.0,16.0,100.0,100.0,64.0,8.0,4.0,8.0,['files/p1999/p19999464/s44488939/44488939'],files/p1999/p19999464/s44488939/44488939
185375,448966,167405,19999784,24935234.0,37972930,2119-07-09 17:38:00,2119-07-10 00:04:00,57,M,2119,...,76.0,16.0,99.0,142.0,80.0,3.0,0.0,1.0,['files/p1999/p19999784/s40734999/40734999'],files/p1999/p19999784/s40734999/40734999
185376,448967,167406,19999784,25715748.0,34149746,2119-08-11 09:15:00,2119-08-11 13:40:00,57,M,2119,...,72.0,16.0,100.0,131.0,92.0,0.0,1.0,8.0,['files/p1999/p19999784/s47639679/47639679'],files/p1999/p19999784/s47639679/47639679
185377,448969,167408,19999828,25744818.0,32917002,2149-01-08 09:11:00,2149-01-08 18:12:00,46,F,2147,...,109.0,15.0,96.0,111.0,78.0,4.0,8.0,11.0,['files/p1999/p19999828/s40643529/40643529'],files/p1999/p19999828/s40643529/40643529

In [13]:
structured_train

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,ed_pain_last,n_med,n_medrecon,triage_MAP,score_CCI,score_CART,score_REMS,score_NEWS,score_NEWS2,score_MEWS
0,215414,18566742,27103162.0,38538786,2135-07-16 16:08:00,2135-07-17 01:49:00,58,F,2132,NaN,...,2.127651,5.0,2.0,97.333333,2,4,3,1,1,1
1,205452,16853729,NaN,30043998,2178-01-25 05:09:00,2178-01-25 07:05:00,91,F,2169,NaN,...,2.127651,2.0,3.0,118.333333,7,9,8,1,0,1
2,200705,16026698,NaN,39475313,2128-10-19 20:01:00,2128-10-19 20:16:00,23,M,2128,NaN,...,7.000000,1.0,1.0,116.000000,0,12,4,4,4,4
3,87038,15398519,25237915.0,35495155,2147-06-15 09:50:00,2147-06-15 15:55:00,57,M,2136,NaN,...,0.000000,7.0,10.0,100.000000,12,16,7,5,3,3
4,373626,16787687,23674090.0,31087259,2181-03-20 10:38:00,2181-03-21 12:55:00,87,F,2176,NaN,...,0.000000,6.0,13.0,87.000000,11,9,6,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359038,113182,10249080,NaN,32475431,2116-01-19 23:41:00,2116-01-19 23:55:00,29,M,2114,NaN,...,0.000000,0.0,0.0,98.666667,0,0,0,0,0,1
359039,323227,17819662,21020261.0,31105287,2182-02-08 00:32:00,2182-02-08 03:31:00,52,M,2182,NaN,...,2.127651,2.0,7.0,115.333333,1,0,4,0,0,1
359040,129321,13199993,24770260.0,37954239,2185-03-02 19:21:00,2185-03-04 15:48:00,37,M,2179,NaN,...,0.000000,7.0,0.0,116.666667,0,0,2,0,0,1
359041,167557,10028683,NaN,31802829,2171-12-05 17:36:00,2171-12-05 17:42:00,35,F,2169,NaN,...,0.000000,3.0,10.0,85.000000,1,0,0,0,0,1
359042,300451,13723460,25859289.0,39195476,2161-10-09 20:46:00,2161-10-10 01:26:00,87,M,2160,NaN,...,0.000000,3.0,0.0,96.622249,18,9,6,0,0,1

In [14]:
structured_test

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,ed_pain_last,n_med,n_medrecon,triage_MAP,score_CCI,score_CART,score_REMS,score_NEWS,score_NEWS2,score_MEWS
0,335316,10000032,29079034.0,32952584,2180-07-22 16:24:00,2180-07-23 05:54:00,52,F,2180,NaN,...,0.000000,2.0,14.0,52.333333,6,4,4,3,3,2
1,56672,10000084,29888819.0,36954971,2160-12-27 18:32:00,2160-12-28 16:07:00,72,M,2160,NaN,...,0.000000,1.0,6.0,85.000000,4,9,5,1,0,1
2,0,10000115,NaN,38081480,2154-12-10 02:04:00,2154-12-10 02:16:00,24,M,2154,NaN,...,0.000000,0.0,0.0,87.333333,0,0,0,0,0,1
3,335319,10000117,22927623.0,32642808,2181-11-14 21:51:00,2181-11-15 02:06:42,48,F,2174,NaN,...,0.000000,0.0,1.0,104.666667,1,4,3,0,0,1
4,335320,10000117,NaN,30632130,2183-07-17 10:30:00,2183-07-17 10:40:00,48,F,2174,NaN,...,0.000000,0.0,0.0,70.000000,1,8,5,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89756,223462,19999156,22917423.0,39012698,2123-01-27 13:13:00,2123-01-27 21:39:00,62,F,2123,NaN,...,0.000000,1.0,1.0,104.333333,2,4,3,0,0,1
89757,111942,19999175,NaN,34469189,2185-08-13 20:35:00,2185-08-13 22:24:00,21,M,2185,NaN,...,2.127651,0.0,0.0,93.000000,0,0,2,0,0,1
89758,448969,19999270,NaN,30502357,2184-02-11 21:11:00,2184-02-11 21:14:00,33,M,2184,NaN,...,0.000000,0.0,0.0,71.000000,0,4,0,1,1,1
89759,56670,19999466,21397174.0,30402875,2116-08-30 12:11:00,2116-08-31 21:49:00,33,M,2116,NaN,...,0.000000,3.0,0.0,134.333333,0,0,3,0,0,1
89760,167407,19999828,29734428.0,30712109,2147-07-17 17:18:00,2147-07-18 17:34:00,46,F,2147,NaN,...,9.000000,11.0,8.0,85.666667,0,0,2,1,1,1

In [16]:
structured_train["split"] = "train"
structured_test["split"] = "test"

structured_full = pd.concat([structured_train, structured_test], ignore_index=True)

In [17]:
structured_full

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,n_med,n_medrecon,triage_MAP,score_CCI,score_CART,score_REMS,score_NEWS,score_NEWS2,score_MEWS,split
0,215414,18566742,27103162.0,38538786,2135-07-16 16:08:00,2135-07-17 01:49:00,58,F,2132,NaN,...,5.0,2.0,97.333333,2,4,3,1,1,1,train
1,205452,16853729,NaN,30043998,2178-01-25 05:09:00,2178-01-25 07:05:00,91,F,2169,NaN,...,2.0,3.0,118.333333,7,9,8,1,0,1,train
2,200705,16026698,NaN,39475313,2128-10-19 20:01:00,2128-10-19 20:16:00,23,M,2128,NaN,...,1.0,1.0,116.000000,0,12,4,4,4,4,train
3,87038,15398519,25237915.0,35495155,2147-06-15 09:50:00,2147-06-15 15:55:00,57,M,2136,NaN,...,7.0,10.0,100.000000,12,16,7,5,3,3,train
4,373626,16787687,23674090.0,31087259,2181-03-20 10:38:00,2181-03-21 12:55:00,87,F,2176,NaN,...,6.0,13.0,87.000000,11,9,6,0,0,0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448799,223462,19999156,22917423.0,39012698,2123-01-27 13:13:00,2123-01-27 21:39:00,62,F,2123,NaN,...,1.0,1.0,104.333333,2,4,3,0,0,1,test
448800,111942,19999175,NaN,34469189,2185-08-13 20:35:00,2185-08-13 22:24:00,21,M,2185,NaN,...,0.0,0.0,93.000000,0,0,2,0,0,1,test
448801,448969,19999270,NaN,30502357,2184-02-11 21:11:00,2184-02-11 21:14:00,33,M,2184,NaN,...,0.0,0.0,71.000000,0,4,0,1,1,1,test
448802,56670,19999466,21397174.0,30402875,2116-08-30 12:11:00,2116-08-31 21:49:00,33,M,2116,NaN,...,3.0,0.0,134.333333,0,0,3,0,0,1,test
448803,167407,19999828,29734428.0,30712109,2147-07-17 17:18:00,2147-07-18 17:34:00,46,F,2147,NaN,...,11.0,8.0,85.666667,0,0,2,1,1,1,test

In [18]:
len(structured_full)

448804

In [19]:
structured_full["stay_id"].nunique()

448804

In [20]:
structured_full = structured_full.merge(
    df_notes[["stay_id", "notes"]],
    on="stay_id",
    how="left"
)

structured_full = structured_full.merge(
    df_ecg[["stay_id", "ecg_paths"]],
    on="stay_id",
    how="left"
)

In [21]:
structured_full

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,triage_MAP,score_CCI,score_CART,score_REMS,score_NEWS,score_NEWS2,score_MEWS,split,notes,ecg_paths
0,215414,18566742,27103162.0,38538786,2135-07-16 16:08:00,2135-07-17 01:49:00,58,F,2132,NaN,...,97.333333,2,4,3,1,1,1,train,NaN,NaN
1,205452,16853729,NaN,30043998,2178-01-25 05:09:00,2178-01-25 07:05:00,91,F,2169,NaN,...,118.333333,7,9,8,1,0,1,train,contrast material through percutaneous gastros...,['files/p1685/p16853729/s46473969/46473969']
2,200705,16026698,NaN,39475313,2128-10-19 20:01:00,2128-10-19 20:16:00,23,M,2128,NaN,...,116.000000,0,12,4,4,4,4,train,left elbow the lateral radiograph of the elbow...,NaN
3,87038,15398519,25237915.0,35495155,2147-06-15 09:50:00,2147-06-15 15:55:00,57,M,2136,NaN,...,100.000000,12,16,7,5,3,3,train,shortness of breath year old man with a histor...,['files/p1539/p15398519/s40039409/40039409']
4,373626,16787687,23674090.0,31087259,2181-03-20 10:38:00,2181-03-21 12:55:00,87,F,2176,NaN,...,87.000000,11,9,6,0,0,0,train,multiple patients with same last name on the r...,['files/p1678/p16787687/s44626801/44626801']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448799,223462,19999156,22917423.0,39012698,2123-01-27 13:13:00,2123-01-27 21:39:00,62,F,2123,NaN,...,104.333333,2,4,3,0,0,1,test,NaN,NaN
448800,111942,19999175,NaN,34469189,2185-08-13 20:35:00,2185-08-13 22:24:00,21,M,2185,NaN,...,93.000000,0,0,2,0,0,1,test,NaN,NaN
448801,448969,19999270,NaN,30502357,2184-02-11 21:11:00,2184-02-11 21:14:00,33,M,2184,NaN,...,71.000000,0,4,0,1,1,1,test,NaN,NaN
448802,56670,19999466,21397174.0,30402875,2116-08-30 12:11:00,2116-08-31 21:49:00,33,M,2116,NaN,...,134.333333,0,0,3,0,0,1,test,NaN,NaN
448803,167407,19999828,29734428.0,30712109,2147-07-17 17:18:00,2147-07-18 17:34:00,46,F,2147,NaN,...,85.666667,0,0,2,1,1,1,test,NaN,NaN

In [22]:
structured_full = structured_full[
    structured_full["notes"].notna() & structured_full["ecg_paths"].notna()
]

In [23]:
len(structured_full)

162620

In [24]:
structured_full["subject_id"].nunique()

62123

In [25]:
print(structured_full["outcome_hospitalization"].value_counts())

outcome_hospitalization
True     96929
False    65691
Name: count, dtype: int64

In [26]:
# shuffle rows
structured_full = structured_full.sample(frac=1, random_state=42).reset_index(drop=True)

n = len(structured_full)

train_end = int(0.8 * n)
val_end = int(0.9 * n)

train_df = structured_full.iloc[:train_end]
val_df   = structured_full.iloc[train_end:val_end]
test_df  = structured_full.iloc[val_end:]

In [27]:
train_df.to_csv("mv_train.csv", index=False)
val_df.to_csv("mv_val.csv", index=False)
test_df.to_csv("mv_test.csv", index=False)

In [27]:
len(test_df)

16262

In [28]:
len(val_df)

16262

In [29]:
train_df

,index,subject_id,hadm_id,stay_id,intime,outtime,anchor_age,gender,anchor_year,dod,...,triage_MAP,score_CCI,score_CART,score_REMS,score_NEWS,score_NEWS2,score_MEWS,split,notes,ecg_paths
0,69219,12174269,NaN,32252456,2115-03-05 18:52:00,2115-03-05 18:54:00,30,F,2115,NaN,...,94.666667,0,0,0,0,0,1,train,examination ankle ap mortise and lat left indi...,['files/p1217/p12174269/s47575777/47575777']
1,374706,16975219,NaN,36792323,2123-11-26 04:52:00,2123-11-26 06:13:00,47,M,2121,NaN,...,111.333333,1,4,6,3,2,3,train,indication year old man with right shoulder pa...,['files/p1697/p16975219/s49058539/49058539']
2,392693,10199379,NaN,38089639,2161-04-10 13:43:00,2161-04-10 13:49:00,30,F,2157,NaN,...,106.333333,1,0,0,0,0,1,test,i ve been getting more i scheduled an appointm...,['files/p1019/p10199379/s41948308/41948308']
3,386691,19101434,25207489.0,33105183,2191-05-10 20:19:00,2191-05-10 22:27:54,64,M,2188,NaN,...,109.000000,3,4,5,1,0,1,train,malaise hypotension baradycardia anemia mr is ...,['files/p1910/p19101434/s44754723/44754723']
4,20499,13593727,25433469.0,34482189,2113-05-24 15:20:00,2113-05-24 20:50:19,52,M,2112,NaN,...,79.666667,4,0,2,0,0,1,train,esrd mr is a year old male with hep c w fibros...,['files/p1359/p13593727/s43147443/43147443']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130089,270105,18344979,22754681.0,33003986,2148-05-17 13:49:00,2148-05-17 21:33:00,70,M,2148,NaN,...,106.666667,3,9,5,0,0,1,test,examination knee ap wb lateral and sunrise lef...,['files/p1834/p18344979/s44647775/44647775']
130090,103723,18521553,24775640.0,38586635,2205-04-24 03:20:00,2205-04-24 10:37:00,88,F,2194,NaN,...,108.666667,4,9,8,1,0,1,train,indication with r knee pain s p fall r knee pa...,['files/p1852/p18521553/s47124485/47124485']
130091,147299,16348266,NaN,39860421,2130-11-08 22:56:00,2130-11-08 23:01:00,37,M,2129,NaN,...,98.666667,0,0,2,0,0,1,train,mr is a with a pmh significant for hiv on haar...,['files/p1634/p16348266/s42455134/42455134']
130092,96861,17224704,21140484.0,36602043,2124-11-24 22:46:00,2124-11-25 08:38:00,70,F,2119,NaN,...,74.333333,3,9,6,2,2,1,train,study ct of the paranasal sinuses with contras...,['files/p1722/p17224704/s47615898/47615898']
130093,257565,16142730,NaN,36957893,2141-12-21 14:16:00,2141-12-21 14:24:00,69,M,2138,NaN,...,103.333333,3,9,5,0,0,1,train,left ankle arthritis with post traumatic left ...,['files/p1614/p16142730/s48861282/48861282']